begin;
create extension if not exists "pgcrypto";
create table if not exists public.dashboard_stats (
  id smallint primary key default 1 check (id = 1),
  overall_risk integer not null check (overall_risk between 0 and 100),
  risk_label text not null,
  today_consults integer not null default 0,
  crop_count integer not null default 0,
  city_count integer not null default 0,
  login_count bigint not null default 0,
  consult_date date not null default ((now() at time zone 'Asia/Shanghai')::date),
  updated_at timestamptz not null default now()
);
alter table public.dashboard_stats
  add column if not exists login_count bigint not null default 0;
alter table public.dashboard_stats
  add column if not exists consult_date date not null
  default ((now() at time zone 'Asia/Shanghai')::date);

create table if not exists public.city_risk (
  id uuid primary key default gen_random_uuid(),
  city text not null unique,
  zone text not null,
  score integer not null check (score between 0 and 100),
  level text not null check (level in ('high', 'medium', 'low')),
  focus text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  level text not null check (level in ('high', 'medium', 'low')),
  date text not null,
  title text not null,
  summary text not null,
  crop text not null,
  region text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.crops (
  code text primary key,
  name text not null unique,
  icon text not null,
  season text not null,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.crop_stages (
  id bigint generated by default as identity primary key,
  crop_code text not null references public.crops(code) on delete cascade,
  name text not null,
  sort_order integer not null,
  unique (crop_code, name),
  unique (crop_code, sort_order)
);

create table if not exists public.prevention_tips (
  id bigint generated by default as identity primary key,
  crop_code text not null references public.crops(code) on delete cascade,
  category text not null,
  content text not null,
  sort_order integer not null,
  updated_at timestamptz not null default now(),
  unique (crop_code, sort_order)
);

create table if not exists public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  crop text,
  growth_stage text,
  city text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  agent text,
  skills_used text[] not null default '{}',
  created_at timestamptz not null default now()
);

-- Web 与未来 Android/iOS 共用的自定义用户名账户。
create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique check (username ~ '^[一-龥A-Za-z0-9_]{2,16}$'),
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_user_sessions (
  session_token uuid primary key default extensions.gen_random_uuid(),
  user_id bigint not null references public.app_users(id) on delete cascade,
  expires_at timestamptz not null default (now() + interval '30 days'),
  created_at timestamptz not null default now()
);

create index if not exists app_user_sessions_user_id_idx
  on public.app_user_sessions(user_id, expires_at desc);

create table if not exists public.diagnosis_history (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete cascade,
  conversation_id text,
  crop text not null,
  growth_stage text not null,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

create index if not exists diagnosis_history_user_created_idx
  on public.diagnosis_history(user_id, created_at desc);

-- 每个自定义账户分别记录已查看的预警，支持 Web 与未来移动端同步未读红标。
create table if not exists public.app_user_alert_reads (
  user_id bigint not null references public.app_users(id) on delete cascade,
  alert_id uuid not null references public.alerts(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (user_id, alert_id)
);

create index if not exists app_user_alert_reads_user_time_idx
  on public.app_user_alert_reads(user_id, read_at desc);

alter table public.dashboard_stats enable row level security;
alter table public.city_risk enable row level security;
alter table public.alerts enable row level security;
alter table public.crops enable row level security;
alter table public.crop_stages enable row level security;
alter table public.prevention_tips enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.app_users enable row level security;
alter table public.app_user_sessions enable row level security;
alter table public.diagnosis_history enable row level security;
alter table public.app_user_alert_reads enable row level security;

drop policy if exists "public can read dashboard stats" on public.dashboard_stats;
drop policy if exists "public can read city risk" on public.city_risk;
drop policy if exists "public can read alerts" on public.alerts;
drop policy if exists "public can read crops" on public.crops;
drop policy if exists "public can read crop stages" on public.crop_stages;
drop policy if exists "public can read prevention tips" on public.prevention_tips;
drop policy if exists "users manage own sessions" on public.chat_sessions;
drop policy if exists "users manage messages in own sessions" on public.chat_messages;

create policy "public can read dashboard stats" on public.dashboard_stats for select using (true);
create policy "public can read city risk" on public.city_risk for select using (true);
create policy "public can read alerts" on public.alerts for select using (true);
create policy "public can read crops" on public.crops for select using (enabled = true);
create policy "public can read crop stages" on public.crop_stages for select using (true);
create policy "public can read prevention tips" on public.prevention_tips for select using (true);
create policy "users manage own sessions" on public.chat_sessions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage messages in own sessions" on public.chat_messages
  for all using (
    exists (select 1 from public.chat_sessions s where s.id = session_id and s.user_id = auth.uid())
  ) with check (
    exists (select 1 from public.chat_sessions s where s.id = session_id and s.user_id = auth.uid())
  );

grant select on public.dashboard_stats, public.city_risk, public.alerts, public.crops,
  public.crop_stages, public.prevention_tips to anon, authenticated;
grant select, insert, update, delete on public.chat_sessions, public.chat_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- 自定义账户表不开放直接读写，浏览器只能调用下方安全函数。
revoke all on public.app_users from anon, authenticated;
revoke all on public.app_user_sessions from anon, authenticated;
revoke all on public.diagnosis_history from anon, authenticated;
revoke all on public.app_user_alert_reads from anon, authenticated;

create or replace function public.register_app_user(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  normalized_username text := lower(trim(p_username));
begin
  if normalized_username !~ '^[一-龥A-Za-z0-9_]{2,16}$' then
    raise exception '用户名须为 2–16 位中文、英文、数字或下划线。';
  end if;
  if char_length(p_password) < 6 then
    raise exception '密码至少需要 6 位。';
  end if;
  if exists (select 1 from public.app_users where username = normalized_username) then
    raise exception '该用户名已被注册，请换一个。';
  end if;

  insert into public.app_users (username, password_hash)
  values (normalized_username, extensions.crypt(p_password, extensions.gen_salt('bf', 10)));

  return jsonb_build_object('username', normalized_username);
end;
$$;

create or replace function public.login_app_user(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  matched_user public.app_users%rowtype;
  new_token uuid;
begin
  select * into matched_user
  from public.app_users
  where username = lower(trim(p_username));

  if not found or extensions.crypt(p_password, matched_user.password_hash) <> matched_user.password_hash then
    raise exception '用户名或密码不正确，请先注册或重新输入。';
  end if;

  delete from public.app_user_sessions where expires_at < now();
  insert into public.app_user_sessions (user_id)
  values (matched_user.id)
  returning session_token into new_token;

  update public.dashboard_stats
  set login_count = login_count + 1,
      updated_at = now()
  where id = 1;

  return jsonb_build_object(
    'id', matched_user.id,
    'username', matched_user.username,
    'session_token', new_token
  );
end;
$$;

create or replace function public.logout_app_user(p_session_token uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.app_user_sessions where session_token = p_session_token;
  return found;
end;
$$;

create or replace function public.save_diagnosis_history(
  p_session_token uuid,
  p_conversation_id text,
  p_crop text,
  p_growth_stage text,
  p_question text,
  p_answer text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id bigint;
  new_id bigint;
begin
  select user_id into current_user_id
  from public.app_user_sessions
  where session_token = p_session_token and expires_at > now();

  if current_user_id is null then
    raise exception '登录已失效，请重新登录。';
  end if;

  insert into public.diagnosis_history
    (user_id, conversation_id, crop, growth_stage, question, answer)
  values
    (current_user_id, nullif(trim(p_conversation_id), ''), trim(p_crop),
     trim(p_growth_stage), trim(p_question), trim(p_answer))
  returning id into new_id;

  update public.dashboard_stats
  set today_consults = case
        when consult_date = (now() at time zone 'Asia/Shanghai')::date then today_consults + 1
        else 1
      end,
      consult_date = (now() at time zone 'Asia/Shanghai')::date,
      updated_at = now()
  where id = 1;

  return new_id;
end;
$$;

create or replace function public.get_diagnosis_history(
  p_session_token uuid,
  p_limit integer default 20
)
returns table (
  id bigint,
  conversation_id text,
  crop text,
  growth_stage text,
  question text,
  answer text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id bigint;
begin
  select user_id into current_user_id
  from public.app_user_sessions
  where session_token = p_session_token and expires_at > now();

  if current_user_id is null then
    raise exception '登录已失效，请重新登录。';
  end if;

  return query
  select h.id, h.conversation_id, h.crop, h.growth_stage,
         h.question, h.answer, h.created_at
  from public.diagnosis_history h
  where h.user_id = current_user_id
  order by h.created_at desc
  limit greatest(1, least(coalesce(p_limit, 20), 50));
end;
$$;

create or replace function public.get_unread_alert_count(p_session_token uuid)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id bigint;
  unread_count bigint;
begin
  select user_id into current_user_id
  from public.app_user_sessions
  where session_token = p_session_token and expires_at > now();

  if current_user_id is null then
    raise exception '登录已失效，请重新登录。';
  end if;

  select count(*) into unread_count
  from public.alerts a
  where not exists (
    select 1 from public.app_user_alert_reads r
    where r.user_id = current_user_id and r.alert_id = a.id
  );

  return unread_count;
end;
$$;

create or replace function public.mark_alerts_read(p_session_token uuid)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id bigint;
  inserted_count bigint;
begin
  select user_id into current_user_id
  from public.app_user_sessions
  where session_token = p_session_token and expires_at > now();

  if current_user_id is null then
    raise exception '登录已失效，请重新登录。';
  end if;

  insert into public.app_user_alert_reads (user_id, alert_id)
  select current_user_id, a.id from public.alerts a
  on conflict (user_id, alert_id) do nothing;

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

grant execute on function public.register_app_user(text, text) to anon, authenticated;
grant execute on function public.login_app_user(text, text) to anon, authenticated;
grant execute on function public.logout_app_user(uuid) to anon, authenticated;
grant execute on function public.save_diagnosis_history(uuid, text, text, text, text, text) to anon, authenticated;
grant execute on function public.get_diagnosis_history(uuid, integer) to anon, authenticated;
grant execute on function public.get_unread_alert_count(uuid) to anon, authenticated;
grant execute on function public.mark_alerts_read(uuid) to anon, authenticated;

insert into public.dashboard_stats
  (id, overall_risk, risk_label, today_consults, crop_count, city_count, login_count, consult_date, updated_at)
values (1, 62, '中风险', 128, 5, 16, 0, (now() at time zone 'Asia/Shanghai')::date, now())
on conflict (id) do nothing;

insert into public.city_risk (city, zone, score, level, focus) values
on conflict (city) do update set
  zone = excluded.zone, score = excluded.score, level = excluded.level,
  focus = excluded.focus, updated_at = now();

insert into public.alerts (slug, level, date, title, summary, crop, region) values
on conflict (slug) do update set
  level = excluded.level, date = excluded.date, title = excluded.title,
  summary = excluded.summary, crop = excluded.crop, region = excluded.region;

insert into public.crops (code, name, icon, season, sort_order, enabled) values
on conflict (code) do update set
  name = excluded.name, icon = excluded.icon, season = excluded.season,
  sort_order = excluded.sort_order, enabled = excluded.enabled, updated_at = now();

insert into public.crop_stages (crop_code, name, sort_order) values
on conflict (crop_code, sort_order) do update set name = excluded.name;

insert into public.prevention_tips (crop_code, category, content, sort_order) values
on conflict (crop_code, sort_order) do update set
  category = excluded.category, content = excluded.content, updated_at = now();

commit;
select
  (select count(*) from public.dashboard_stats) as dashboard_stats,
  (select count(*) from public.city_risk) as city_risk,
  (select count(*) from public.alerts) as alerts,
  (select count(*) from public.crops) as crops,
  (select count(*) from public.crop_stages) as crop_stages,
  (select count(*) from public.prevention_tips) as prevention_tips;
